Device:
    Name: Clima

Coprocessor:
    AutomaticallyStartNetwork: true
    AutomaticallyReconnect: true
    MaximumRetryCount: 7

Network:
    DefaultInterface: WiFi
    GetNetworkTimeAtStartup: true
    NtpRefreshPeriodSeconds: 600
    NtpServers:
        - 0.pool.ntp.org
        - 1.pool.ntp.org
        - 2.pool.ntp.org
        - 3.pool.ntp.org

