name: Develop Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Checkout Meadow.Logging
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/Meadow.Logging
        path: Meadow.Logging
        ref: develop
        
    - name: Checkout Meadow.Units
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/Meadow.Units
        path: Meadow.Units
        ref: develop

    - name: Checkout Meadow.Contracts
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/Meadow.Contracts
        path: Meadow.Contracts
        ref: develop
    
    - name: Checkout Meadow.Core
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/Meadow.Core
        path: Meadow.Core
        ref: develop
        
    - name: Checkout MQTTnet
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/MQTTnet
        path: MQTTnet
        ref: develop
        
    - name: Checkout Meadow.Modbus
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/Meadow.Modbus
        path: Meadow.Modbus
        ref: develop
        
    - name: Checkout Meadow.Foundation
      uses: actions/checkout@v3
      with:
        repository: WildernessLabs/Meadow.Foundation
        path: Meadow.Foundation
        ref: develop

    - name: Checkout Maple
      uses: actions/checkout@v3
      with:
          repository: WildernessLabs/Maple
          path: Maple
          ref: develop

    - name: Checkout Clima
      uses: actions/checkout@v3
      with:
        path: Clima

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 
          6.x

    - name: Install Java SDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version:
          7.0.x

    - name: Install MAUI Workload
      run: dotnet workload install maui --ignore-failed-sources

    - name: Install MAUI Android Workload
      run: dotnet workload install maui-android --ignore-failed-sources
    
    - name: Build Meadow.Clima
      run: dotnet build -c Release Clima/Source/Meadow.Clima.sln
